TOKEN = 'YOUR_TOKEN'
ADMIN_ID = 'YOUR_ID'
POSTGRES_URL="YOUT_URL"
POSTGRES_PRISMA_URL="YOUR_URL"
POSTGRES_URL_NO_SSL="YOUR_URL"
POSTGRES_URL_NON_POOLING="YOUR_URL"
POSTGRES_USER="YOUR_NAME"
POSTGRES_HOST="YOUR_HOST"
POSTGRES_PASSWORD="YOUR_pASSWORD"
POSTGRES_DATABASE="YOUR_DBNAME"

